In [1]:
from IPython.display import clear_output
clear_output()
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button, RadioButtons
from ipywidgets import interact, interactive, fixed, interact_manual, Layout
import ipywidgets as widgets
from mpl_toolkits.mplot3d import axes3d
from sympy import *
from sympy.physics.quantum.dagger import Dagger
from IPython.display import Javascript
import seaborn as sns
import scipy as sc
import sys
np.set_printoptions(threshold=sys.maxsize)

In [80]:
def trace_G(G): #A trace function for just 4x4 G matrices
    return (G[0,0] + G[1,1] + G[2,2] + G[3,3])

In [55]:
C,B=np.around(sc.linalg.schur(A),7)

In [56]:
B

array([[-0.5773369-0.j       ,  0.2958531-0.j       ,
        -0.5601713-0.j       , -0.5151322-0.j       ],
       [-0.5617174-0.1360439j,  0.2547486-0.1240831j,
         0.0261501+0.143854j ,  0.7474194-0.0752237j],
       [-0.4619914+0.0082306j, -0.4586868+0.5869851j,
         0.3725206+0.2609794j, -0.150747 +0.0440981j],
       [-0.3400017-0.0595219j, -0.1476454-0.505404j ,
         0.4405043-0.5137163j, -0.1827563+0.3350751j]])

In [57]:
B.dot(Dagger(B))

array([[ 1.00000002e+00+0.00000000e+00j,  1.00659100e-08-6.15802400e-08j,
         5.59682000e-08-1.13596300e-08j, -3.33217400e-08-3.24968005e-09j],
       [ 1.00659100e-08+6.15802400e-08j,  1.00000001e+00+0.00000000e+00j,
         6.11196200e-08-5.66726600e-08j, -7.55990997e-09-5.61930900e-08j],
       [ 5.59682000e-08+1.13596300e-08j,  6.11196200e-08+5.66726600e-08j,
         1.00000003e+00+0.00000000e+00j,  3.26333299e-08-4.53055000e-09j],
       [-3.33217400e-08+3.24968005e-09j, -7.55990997e-09+5.61930900e-08j,
         3.26333299e-08+4.53055000e-09j,  1.00000004e+00+0.00000000e+00j]])

In [77]:
aux=np.diag(np.random.rand(4))
aux

array([[0.57396864, 0.        , 0.        , 0.        ],
       [0.        , 0.56161716, 0.        , 0.        ],
       [0.        , 0.        , 0.75835984, 0.        ],
       [0.        , 0.        , 0.        , 0.22748753]])

In [90]:
def randG():
    A=np.random.rand(4,4)+np.random.rand(4,4)*1j
    A=A+Dagger(A)
    C,B=np.around(sc.linalg.schur(A),7)
    aux=np.diag(np.random.rand(4))
    G=B.dot(aux).dot(Dagger(B))
    G=G/trace_G(G)
    G=np.around(G,7)    
    return G

In [97]:
randG()

array([[ 0.2648628+0.j       , -0.0455927+0.0210877j,
        -0.0046928+0.0712872j, -0.1294228-0.0160889j],
       [-0.0455927-0.0210877j,  0.3044973+0.j       ,
        -0.109162 -0.0677937j, -0.0574981+0.0742426j],
       [-0.0046928-0.0712872j, -0.109162 +0.0677937j,
         0.1976232+0.j       ,  0.0316973-0.0020614j],
       [-0.1294228+0.0160889j, -0.0574981-0.0742426j,
         0.0316973+0.0020614j,  0.2330167+0.j       ]])

In [242]:
np.around(np.linalg.eig(randG())[0],7)

array([0.0334098+0.j, 0.2486326-0.j, 0.356149 -0.j, 0.3618086-0.j])